run:
  deadline: 10m
  skip-files: [ ]

linters-settings:
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - wrapcheck
    - exhaustivestruct
    - testpackage
    - paralleltest
    - tparallel
    - gomnd

issues:
  exclude-rules:
    - path: sni.go
      text: "G402: TLS MinVersion too low."
    - path: sni_test.go
      text: "G402: TLS MinVersion too low."
