run:
  deadline: 10m
  skip-files: [ ]

linters-settings:
  godox:
    keywords:
      - FIXME

  funlen:
    lines: -1
    statements: 50

linters:
  enable-all: true
  disable:
    - maligned # Deprecated.
    - interfacer # Deprecated.
    - scopelint # Deprecated.
    - golint # Deprecated.
    - ireturn
    - wrapcheck
    - exhaustivestruct
    - testpackage
    - paralleltest
    - tparallel
    - gomnd
    - goerr113
    - wsl
    - nilnil
    - varnamelen

issues:
  exclude-rules:
    - path: sni.go
      text: "G402: TLS MinVersion too low."
    - path: sni_test.go
      text: "G402: TLS MinVersion too low."
    - path: mux_test.go
      text: "G402: TLS MinVersion too low."
