run:
  deadline: 10m
  skip-files: [ ]

linters:
  enable-all: true
  disable:
    - 'maligned' # deprecated
    - 'interfacer' # deprecated
    - 'scopelint' # deprecated
    - 'golint' # deprecated
    - 'wrapcheck'
    - 'exhaustivestruct'

issues:
  exclude-rules:
    - path: sni.go
      text: "G402: TLS MinVersion too low."
