name: build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.16, 1.17]

    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}

      - run: go mod download
      - run: go test -v ./...
